### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Insipidgamr** [SleepingTea98/Spellbound-Modpack#12]
The server seems to not work until someone does @server Restart ive had to do it twice in the past hour, after crashing the server doesnt come back up till someone uses the command. Not sure if theres a bug or out of memory, just wanted to help let the higher ups know

**Comment by SleepingTea98** [comment]
Thanks, we know of this issue.

The server does an auto restart when it has crashed, but sometimes the server just freezes, meaning the restart can't kick in. It takes a staff member to force stop the server and reboot it to fix this issue.

I working on a fix for this now.
