### ISSUE TITLE
Redstone Clocks Do not Function

### ISSUE THREAD

**Issue by Veggies** [SleepingTea98/Spellbound-Modpack#15]
Clocks from Biblio
Redstone Clock from Extra Utilities
Vanilla redstone design clock

None of these work.

**Comment by Veggies** [comment]
Redstone clocks seem to be working after reboot
Biblio clocks do not work properly still.

**Comment by SleepingTea98** [comment]
Thanks for letting us know. Could be an issue with the server running slow.
