### ISSUE TITLE
Immersive Engineering Assembly will not craft

### ISSUE THREAD

**Issue by Veggies** [SleepingTea98/Spellbound-Modpack#16]
The assembly is intended to craft any crafting recipe (If it works in the crafting table, it should work in the machine). The machine works perfectly find crafting steel stuff (All I tested), but cannot craft iron or coal blocks (Also all that was tested).

**Comment by Crack3dC0d3** [comment]
You can use a factorizer from thermal, That block converts 9 of any resource with a block form in a block and backwards

**Comment by SleepingTea98** [comment]
The mod is being removed in the next update, so I'm closing the issue.
