### ISSUE TITLE
Kits duping after placed

### ISSUE THREAD

**Issue by DaniRaina** [SleepingTea98/Spellbound-Modpack#19]
![duping stuff](https://user-images.githubusercontent.com/50417805/57390675-ebfa8480-718a-11e9-9fab-934304d5a9cb.png)

Username: DaniRaina

My Botania weekly kit duped after I placed it.the issue also  seems to exist with blocks as well.

**Comment by SleepingTea98** [comment]
Same issue as https://github.com/SleepingTea98/Spellbound-Modpack/issues/18
