### ISSUE TITLE
Server Download

### ISSUE THREAD

**Issue by luki12163** [SleepingTea98/Spellbound-Modpack#21]
I tried to create my own server to play with friend but when I joining it, is saying that "luki12163 lost connection: You have been disconnected due to an illegal client. Please contact staff."

![Capture](https://user-images.githubusercontent.com/50342726/57569355-dfc13200-73eb-11e9-8fba-defdaac8c3d5.PNG)

**Comment by Crack3dC0d3** [comment]
If its your own server, You can remove the Kinetic-AntiCheat mod from the server. That fixes the issue
