### ISSUE TITLE
RFTools Spawners broken.

### ISSUE THREAD

**Issue by Rdrazga** [SleepingTea98/Spellbound-Modpack#22]
The latest update to spellbound which included and update to RFTools has a glitch that causes the RFTools spawner to no longer take in the organic resource required to spawn mobs, thus breaking the spawner. If there is a different version of the mod available that fixes this issue it would be great to have that as rftools is one of the few ways to auto-spawn withers for supremium.

**Comment by Crack3dC0d3** [comment]
Have you tried replacing the spawner? Or replacing the cables/fluiducts etc?

**Comment by Crack3dC0d3** [comment]
If that doesnt fix it please report it to the mod developer
