### ISSUE TITLE
Some Non-Vanilla dimensions cannot be accessed by the intended method

### ISSUE THREAD

**Issue by Master-Bw3** [SleepingTea98/Spellbound-Modpack#26]
The first dimension that cannot be accessed is the spectre dimension. right clicking the spectre key for 5 seconds does nothing instead of sending the player to that dimension.

The second dimension is the howlingmoon dimension. When trying to sleep in bed with a moon pearl at/past level 5, you don;t get sent to the dimension, but when you leave the bed you get a loading screen and end up in the overworld. Right clicking blocks will make them disappear until the player relogs into the server.

**Comment by AmbresNox** [comment]
This has been happening to me and another friend too
