### ISSUE TITLE
Dark Steel Upgrade "Thaumaturge's Boots" have no crafting recipe.

### ISSUE THREAD

**Issue by ThyCat** [SleepingTea98/Spellbound-Modpack#44]
Enderio has Dark Steel Armor Upgrades and I was crafting the Thaumaturge upgrades for the enderio armor, but the boots upgrade item didn't have a crafting recipe. The chestplate and leggings upgrade just simply combined a Blank Dark Steel Upgrade with the corresponding Thaumaturge armour.

**Comment by SleepingTea98** [comment]
This is an issue with the mod, please report it to the mod maker
