### ISSUE TITLE
Thermal aqueous acumulator dupe

### ISSUE THREAD

**Issue by xerina** [SleepingTea98/Spellbound-Modpack#8]
when i place this block and try to click on it it places another one of itself on top of it which can be broken and picked up as a easy dupe i started with one from the thermal ot kit that came with my bronze rank now i have like 5 (i was testing to make sure it was a bug) and ill get rid of them (lava probably) this bug may be a problem with all thermal blocks but i haven't tested the others yet.

**Comment by SleepingTea98** [comment]
Thanks for letting us know!
